# Generated by Django 3.1.3 on 2022-10-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='mobile',
        ),
    ]
