# Generated by Django 3.1.3 on 2022-10-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20221021_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='Balance',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
