# Generated by Django 3.1.3 on 2022-10-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20221023_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdetails',
            name='pan_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.buyer'),
        ),
    ]
