# Generated by Django 3.1.3 on 2022-10-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20221023_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdetails',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ownerdetails',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
