# Generated by Django 3.1.3 on 2024-07-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20240705_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='Balance',
            new_name='balance',
        ),
    ]
