# Generated by Django 5.2.3 on 2025-06-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20250628_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular Staff'), ('admin', 'Administrative Staff'), ('super', 'System Administrator')], default='regular', max_length=20),
        ),
        migrations.DeleteModel(
            name='OwnerProfile',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
