# Generated by Django 5.2.3 on 2025-07-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchasebill_purchase_bill_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='bill',
            new_name='purchase_bill_number',
        ),
    ]
