# Generated by Django 5.2.3 on 2025-07-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_rename_bill_purchaseitem_purchase_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_bill_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
