# Generated by Django 3.1.3 on 2020-11-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kTradersApp', '0002_auto_20201122_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
