# Generated by Django 3.1.3 on 2020-11-22 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kTradersApp', '0003_auto_20201122_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
