# Generated by Django 3.1.3 on 2020-11-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kTradersApp', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
