# Generated by Django 3.1.3 on 2024-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kTradersApp', '0006_auto_20221031_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
