# Generated by Django 3.1.3 on 2020-11-26 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kTradersApp', '0007_auto_20201125_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateField(default=datetime.date(2020, 11, 26)),
        ),
    ]
