# Generated by Django 3.1.3 on 2020-11-26 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kTradersApp', '0008_auto_20201126_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
