# Generated by Django 3.1.3 on 2020-11-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kTradersApp', '0009_auto_20201126_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticularsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField(unique=True)),
                ('particulars', models.CharField(max_length=255)),
                ('quantity', models.SmallIntegerField()),
                ('rate', models.SmallIntegerField()),
                ('total_amt', models.IntegerField()),
                ('total_package', models.IntegerField()),
                ('fare_per_package_rate', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bill_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kTradersApp.particularsdetail'),
        ),
    ]
