# Generated by Django 3.1.3 on 2020-11-27 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kTradersApp', '0010_auto_20201127_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particularsdetail',
            name='bill_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kTradersApp.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bill_number',
            field=models.IntegerField(unique=True),
        ),
    ]
