# Generated by Django 3.1.3 on 2020-11-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kTradersApp', '0011_auto_20201127_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particularsdetail',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
