# Generated by Django 3.1.3 on 2020-11-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kTradersApp', '0012_auto_20201127_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='particularsdetail',
            old_name='total_amt',
            new_name='goods_amount',
        ),
        migrations.RemoveField(
            model_name='particularsdetail',
            name='fare_per_package_rate',
        ),
        migrations.RemoveField(
            model_name='particularsdetail',
            name='total_package',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fare_per_package_rate',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='labour_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_package',
            field=models.IntegerField(default=0),
        ),
    ]
