# Generated by Django 5.2.3 on 2025-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrate',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dailyrate',
            name='sale_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
