# Generated by Django 5.2.3 on 2025-07-02 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_dailyrate_purchase_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrate',
            old_name='sale_rate',
            new_name='sales_rate',
        ),
    ]
