# Generated by Django 3.1.3 on 2022-10-21 04:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kTradersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('bill_number', models.IntegerField(unique=True)),
                ('credit_amount', models.IntegerField(null=True)),
                ('debit_amount', models.IntegerField(null=True)),
                ('pan_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kTradersApp.buyer')),
            ],
        ),
    ]
