# Generated by Django 3.1.3 on 2022-10-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
