# Generated by Django 3.1.3 on 2022-10-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='balance_after_transaction',
            field=models.IntegerField(default=0),
        ),
    ]
