# Generated by Django 3.1.3 on 2024-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20240705_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bill_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
