# Generated by Django 5.2.3 on 2025-07-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesbill_sales_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='sales_bill_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
