# Generated by Django 5.2.3 on 2025-07-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesbill_sales_bill_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitem',
            old_name='bill',
            new_name='sales_bill_number',
        ),
    ]
